### ISSUE TITLE
Misc. MIDI Broken

### ISSUE THREAD

**Issue by d3c1987** [AnAceCase/ProjectMIDI#2]
when you click on the midi link on the misalanios section it brings you to a white screen
![image_2023-03-02_114934641](https://user-images.githubusercontent.com/105604223/222420524-bfbe1f5a-7f78-4459-9612-e0a64bb51bf6.png)

**Comment by AnAceCase** [comment]
Hi! I am aware of this issue, thanks for addressing it, I'll make it redirect to the 404 as there are currently no Miscellaneous MIDIs

Many thanks 

-AnAceCase

**Comment by d3c1987** [comment]
okipoki german man
